### ISSUE TITLE
Injecting AWS SignatrueV4 header

### ISSUE THREAD

**Issue by duzzell** [chuacw/DelphiWebsockets#3]
Thank you for providing this code. It's exactly what I need.

I'd like to inject an AWS SignatureV4 header into the connection request. In order to do that I need the payload of the connection request. Is there a way to access the text of the connection request payload from TIdHTTPWebSocketClient? If not, is there any way to use FCustomHeaderProc to inject a SignatureV4 header?

Thanks

**Comment by chuacw** [comment]
This is for reporting issues, not support.
